# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Submit a new beta build to Firebase App Distribution"
  lane : distribute do
    build_android_app(task: "assemble", build_type: "debug")
          firebase_app_distribution(
              app: "dev.hello.viper",
              testers: "ved.yadav@rootinfosol.com, nikhil@rootinfosol.com",
              firebase_cli_token: "1//0gG2aZ8y1jI5OCgYIARAAGBASNwF-L9IrfDAAiQdbBg46oPMeSVCcz_Ano7hbQtCQDTWwJd48hCW8R3pedPcoPCt-zRJjVVXPmw8"
          )
        end

end
